//go:build kirolive

// Track 3a real-kiro elicitation harness. NOT run in normal CI — build-tag
// gated (mirrors tests/track0_capture_test.go).
//
// Track 0 established the baseline: with the pre-Track-3a gateway, kiro never
// tried a built-in tool (no session/request_permission) and never emitted a
// {"tool_call":…} JSON block — it just refused in prose. Tasks 1-6 added: deny
// kiro's session/request_permission when the caller supplied tools (instead of
// auto-granting), a MAX_TOOL_DENIALS circuit breaker, and a strict
// {"tool_call":…} function-calling prompt. This harness proves — against real
// kiro-cli — that the apparatus actually changes kiro's behavior.
//
// Coercion of the emitted JSON into structured tool_calls is Track 3b, out of
// scope here. Success = the capture shows kiro being denied a built-in tool
// and/or emitting {"tool_call":…} JSON — a behavior change from Track 0.
//
// Prereqs: a gateway running with ACP_CAPTURE=true and real kiro-cli, reachable
// at GW_URL (default http://127.0.0.1:18099). Run:
//
//	KIRO_CMD=kiro-cli KIRO_ARGS=acp ACP_CAPTURE=true HTTP_ADDR=127.0.0.1:18099 \
//	  ENABLED_SURFACES=ollama,anthropic,openai go run ./cmd/otto-gateway &
//	go test -tags kirolive ./tests/ -run TestTrack3aElicitation -v
package tests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"
)

// track3aGWURL mirrors track0's gwURL() helper so this file can be built
// standalone if track0_capture_test.go is ever removed; both are kirolive-
// gated and live in package tests, so having two identically-behaved helpers
// with distinct names avoids a redeclaration error while both files exist.
func track3aGWURL() string {
	if v := os.Getenv("GW_URL"); v != "" {
		return v
	}
	return "http://127.0.0.1:18099"
}

// TestTrack3aElicitation drives one get_weather round-trip per surface against
// a gateway patched with the Track 3a deny/prompt/breaker apparatus, then
// classifies the NEW frames captured for that turn:
//   - permissionRequested: a session/request_permission frame appeared (kiro
//     tried one of its own built-in tools).
//   - permissionDenied: the gateway's response to that frame carried
//     granted:false (the deny path fired, not the old auto-grant).
//   - toolCallJSON: kiro emitted a `{"tool_call"` block in agent_message_chunk
//     text (the elicitation apparatus's target behavior).
//   - stillProseRefusal: neither of the above — the Track 0 regression case.
func TestTrack3aElicitation(t *testing.T) {
	client := &http.Client{Timeout: 150 * time.Second}

	if !track3aFetchCapture(t, client).Enabled {
		t.Fatal("capture is not enabled — start the gateway with ACP_CAPTURE=true")
	}

	var report bytes.Buffer
	fmt.Fprintf(&report, "# Track 3a — live elicitation capture (2026-07-15)\n\n")
	fmt.Fprintf(&report, "Generated by tests/track3a_elicitation_test.go (real kiro, gateway patched\n"+
		"with Tasks 1-6). Each surface drove a `get_weather` tool round-trip against\n"+
		"the SAME prompt Track 0 used; the raw kiro frames captured for that turn are\n"+
		"classified below against the Track 0 baseline (no permission request, no\n"+
		"tool_call, prose refusal).\n\n")

	anyBehaviorChange := false
	var summaries []string

	for _, p := range track3aProbes() {
		before := track3aLastSeq(track3aFetchCapture(t, client))
		resp := track3aDrive(t, client, p)
		// Give kiro's trailing frames (and any permission round-trip) a moment
		// to land in the ring.
		time.Sleep(2 * time.Second)
		frames := track3aNewFramesSince(track3aFetchCapture(t, client), before)

		if len(frames) == 0 {
			t.Errorf("[%s] no frames captured for the round-trip", p.name)
		}

		cls := track3aClassify(frames)
		track3aWriteSection(&report, p.name, resp, frames, cls)

		changed := cls.permissionRequested || cls.toolCallJSON
		if changed {
			anyBehaviorChange = true
		}
		summaries = append(summaries, fmt.Sprintf(
			"%s: permission_requested=%v permission_denied=%v tool_call_json=%v still_prose_refusal=%v",
			p.name, cls.permissionRequested, cls.permissionDenied, cls.toolCallJSON, !changed,
		))
		t.Logf("[%s] permission_requested=%v permission_denied=%v tool_call_json=%v",
			p.name, cls.permissionRequested, cls.permissionDenied, cls.toolCallJSON)
	}

	path := "../docs/reviews/2026-07-14-track0-toolcall-findings.md"
	if err := track3aAppendSection(path, report.String()); err != nil {
		t.Fatalf("append findings section: %v", err)
	}
	t.Logf("appended Track 3a outcome section to %s", path)

	if !anyBehaviorChange {
		t.Errorf("no surface showed a behavior change from Track 0 baseline "+
			"(no session/request_permission frame, no {\"tool_call\" emission) — "+
			"the elicitation apparatus did not fire.\n%s", strings.Join(summaries, "\n"))
	}
}

// --- probes ---------------------------------------------------------------

// track3aProbe is one surface's tool-declaring request. Identical bodies to
// track0's probes() so the two runs are directly comparable.
type track3aProbe struct {
	name    string
	path    string
	headers map[string]string
	body    string
}

func track3aProbes() []track3aProbe {
	weatherPrompt := "What is the weather in Paris? Use the get_weather tool."
	return []track3aProbe{
		{
			name: "anthropic", path: "/v1/messages",
			headers: map[string]string{"anthropic-version": "2023-06-01"},
			body: `{"model":"auto","max_tokens":256,"messages":[{"role":"user","content":"` + weatherPrompt + `"}],` +
				`"tools":[{"name":"get_weather","description":"Get weather for a city",` +
				`"input_schema":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}]}`,
		},
		{
			name: "openai", path: "/v1/chat/completions",
			body: `{"model":"auto","messages":[{"role":"user","content":"` + weatherPrompt + `"}],` +
				`"tools":[{"type":"function","function":{"name":"get_weather","description":"Get weather for a city",` +
				`"parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}}]}`,
		},
		{
			name: "ollama", path: "/api/chat",
			body: `{"model":"auto","stream":false,"messages":[{"role":"user","content":"` + weatherPrompt + `"}],` +
				`"tools":[{"type":"function","function":{"name":"get_weather","description":"Get weather for a city",` +
				`"parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}}]}`,
		},
	}
}

// --- capture plumbing (mirrors track0's helpers, renamed to avoid collision) ---

type track3aFrame struct {
	Seq    uint64 `json:"seq"`
	Method string `json:"method"`
	Params string `json:"params"`
	Bytes  int    `json:"bytes"`
}

type track3aCaptureResp struct {
	Enabled bool           `json:"enabled"`
	Frames  []track3aFrame `json:"frames"`
}

func track3aFetchCapture(t *testing.T, c *http.Client) track3aCaptureResp {
	t.Helper()
	resp, err := c.Get(track3aGWURL() + "/admin/api/acp-capture")
	if err != nil {
		t.Fatalf("GET capture: %v", err)
	}
	defer resp.Body.Close()
	var cr track3aCaptureResp
	if err := json.NewDecoder(resp.Body).Decode(&cr); err != nil {
		t.Fatalf("decode capture: %v", err)
	}
	return cr
}

func track3aDrive(t *testing.T, c *http.Client, p track3aProbe) string {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, track3aGWURL()+p.path, strings.NewReader(p.body))
	if err != nil {
		t.Fatalf("[%s] build req: %v", p.name, err)
	}
	req.Header.Set("Content-Type", "application/json")
	for k, v := range p.headers {
		req.Header.Set(k, v)
	}
	resp, err := c.Do(req)
	if err != nil {
		t.Fatalf("[%s] POST %s: %v", p.name, p.path, err)
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(resp.Body)
	return string(b)
}

func track3aLastSeq(cr track3aCaptureResp) uint64 {
	var max uint64
	for _, f := range cr.Frames {
		if f.Seq > max {
			max = f.Seq
		}
	}
	return max
}

func track3aNewFramesSince(cr track3aCaptureResp, since uint64) []track3aFrame {
	var out []track3aFrame
	for _, f := range cr.Frames {
		if f.Seq > since {
			out = append(out, f)
		}
	}
	return out
}

// --- classification ---------------------------------------------------------

type track3aClassification struct {
	permissionRequested bool // a session/request_permission frame appeared
	permissionDenied    bool // gateway's response to it carried granted:false
	toolCallJSON        bool // agent_message_chunk text contains {"tool_call"
	permissionFrames    []track3aFrame
	toolCallSnippets    []string
}

func track3aClassify(frames []track3aFrame) track3aClassification {
	var cls track3aClassification
	for _, f := range frames {
		if f.Method == "session/request_permission" {
			cls.permissionRequested = true
			cls.permissionFrames = append(cls.permissionFrames, f)
		}
		// The gateway's own response frame to the permission request is not
		// re-emitted as a captured inbound frame (capture is kiro->gateway
		// only, per track0's harness design) — permissionDenied is inferred
		// from the gateway log by the caller/report step, not from the
		// capture ring. Left false here; see track3aWriteSection's note.
		if strings.Contains(f.Method, "update") || strings.Contains(f.Method, "notification") {
			lower := f.Params
			if strings.Contains(lower, `{"tool_call"`) || strings.Contains(lower, `\"tool_call\"`) {
				cls.toolCallJSON = true
				cls.toolCallSnippets = append(cls.toolCallSnippets, first(f.Params, 300))
			}
		}
	}
	return cls
}

func track3aWriteSection(report *bytes.Buffer, surface, clientResp string, frames []track3aFrame, cls track3aClassification) {
	fmt.Fprintf(report, "### %s\n\n", surface)
	fmt.Fprintf(report, "- Frames captured this turn: %d\n", len(frames))
	fmt.Fprintf(report, "- **session/request_permission seen:** %v\n", cls.permissionRequested)
	fmt.Fprintf(report, "- **{\"tool_call\":…} JSON emitted:** %v\n", cls.toolCallJSON)
	stillProse := !cls.permissionRequested && !cls.toolCallJSON
	fmt.Fprintf(report, "- **Still prose refusal (Track 0 regression case):** %v\n", stillProse)
	if len(cls.permissionFrames) > 0 {
		fmt.Fprintf(report, "\n<details><summary>session/request_permission frame(s)</summary>\n\n```json\n")
		for _, f := range cls.permissionFrames {
			fmt.Fprintf(report, "%s\n", f.Params)
		}
		fmt.Fprintf(report, "```\n\n</details>\n")
	}
	if len(cls.toolCallSnippets) > 0 {
		fmt.Fprintf(report, "\n<details><summary>tool_call JSON snippet(s)</summary>\n\n```json\n")
		for _, s := range cls.toolCallSnippets {
			fmt.Fprintf(report, "%s\n", s)
		}
		fmt.Fprintf(report, "```\n\n</details>\n")
	}
	fmt.Fprintf(report, "\n- Client-visible response (first 400 bytes):\n\n```\n%s\n```\n\n", first(clientResp, 400))
	fmt.Fprintf(report, "<details><summary>raw frames</summary>\n\n```json\n")
	for _, f := range frames {
		fmt.Fprintf(report, "%s %s\n", f.Method, first(f.Params, 600))
	}
	fmt.Fprintf(report, "```\n\n</details>\n\n")
}

// track3aAppendSection appends body under a "Track 3a outcome (live,
// 2026-07-15)" heading to the findings doc at path, creating the heading only
// once (idempotent across re-runs within the same test process — a second
// TestMain run would append twice, which is acceptable for a manual live
// harness).
func track3aAppendSection(path, body string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var out bytes.Buffer
	out.Write(existing)
	out.WriteString("\n## Track 3a outcome (live, 2026-07-15)\n\n")
	out.WriteString(body)
	return os.WriteFile(path, out.Bytes(), 0o644)
}
