//go:build kirolive

// Track 3b real-kiro coercion harness. NOT run in normal CI — build-tag
// gated (mirrors tests/track3a_elicitation_test.go).
//
// Track 3a proved (against captured ACP frames) that kiro, under the Track 3a
// deny/prompt/breaker apparatus, emits a `{"tool_call":…}` JSON block instead
// of refusing in prose. That capture-level proof said nothing about what the
// CLIENT actually receives — the raw `{"tool_call":…}` text was still just
// prose content in the HTTP response body. Task 6 of Track 3b closes that
// gap: the gateway's engine-level coercion (CoerceToolCall) now rewrites that
// wrapper JSON into each surface's native structured-tool-call shape before
// the response reaches the client. This harness drives the SAME get_weather
// round-trip per surface as Track 3a and asserts the CLIENT-VISIBLE HTTP
// response body — not the capture frames — now carries a structured tool
// call: Anthropic `content[].type=="tool_use"` + `stop_reason=="tool_use"`,
// OpenAI `choices[0].message.tool_calls[0].function.name` +
// `finish_reason=="tool_calls"` (arguments as a JSON string), and Ollama
// `message.tool_calls[0].function.name` (arguments as a JSON object).
//
// Prereqs: a gateway running with ACP_CAPTURE=true and real kiro-cli, reachable
// at GW_URL (default http://127.0.0.1:18099). Run:
//
//	KIRO_CMD=kiro-cli KIRO_ARGS=acp ACP_CAPTURE=true HTTP_ADDR=127.0.0.1:18099 \
//	  ENABLED_SURFACES=ollama,anthropic,openai go run ./cmd/otto-gateway &
//	go test -tags kirolive ./tests/ -run TestTrack3bCoercion -v
package tests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"
)

// TestTrack3bCoercion drives one get_weather round-trip per surface against a
// live gateway with the Track 3b coercion apparatus in place, then asserts
// the CLIENT-VISIBLE HTTP response body carries a structured tool call in
// that surface's native shape. Reuses track3a's probe bodies, drive helper,
// and GW URL resolver (track3aProbes/track3aDrive/track3aGWURL) — they live
// in package tests under the same kirolive build tag, so this file does not
// redeclare them. Every surface is driven and reported (t.Errorf, not
// t.Fatal, on a per-surface miss) so the findings capture every surface's
// outcome even if one regresses.
func TestTrack3bCoercion(t *testing.T) {
	client := newTrack3bClient()

	if !track3aFetchCapture(t, client).Enabled {
		t.Fatal("capture is not enabled — start the gateway with ACP_CAPTURE=true")
	}

	var report bytes.Buffer
	fmt.Fprintf(&report, "# Track 3b — live structured tool_call verification (2026-07-15)\n\n")
	fmt.Fprintf(&report, "Generated by tests/track3b_coercion_test.go (real kiro, gateway with the\n"+
		"Track 3b `CoerceToolCall` wrapper-coercion apparatus in place). Each surface\n"+
		"drove the SAME `get_weather` round-trip Track 3a used; unlike Track 3a (which\n"+
		"inspected captured ACP frames), this harness asserts the CLIENT-VISIBLE HTTP\n"+
		"response body now carries a STRUCTURED tool call in that surface's native\n"+
		"shape, not raw `{\"tool_call\":…}` prose text.\n\n")

	anyStructured := false
	var summaries []string

	for _, p := range track3aProbes() {
		resp := track3aDrive(t, client, p)
		// Give kiro's trailing frames a moment to land before the next probe.
		time.Sleep(2 * time.Second)

		var ok bool
		var detail string
		switch p.name {
		case "anthropic":
			ok, detail = track3bCheckAnthropic(resp)
		case "openai":
			ok, detail = track3bCheckOpenAI(resp)
		case "ollama":
			ok, detail = track3bCheckOllama(resp)
		default:
			t.Errorf("[%s] unrecognized probe name — no assertion wired up", p.name)
			continue
		}

		if ok {
			anyStructured = true
		} else {
			t.Errorf("[%s] client response did not carry a structured get_weather tool call: %s", p.name, detail)
		}
		t.Logf("[%s] structured_tool_call=%v detail=%s", p.name, ok, detail)

		track3bWriteSection(&report, p.name, resp, ok, detail)
		summaries = append(summaries, fmt.Sprintf("%s: structured_tool_call=%v (%s)", p.name, ok, detail))
	}

	path := "../docs/reviews/2026-07-14-track0-toolcall-findings.md"
	if err := track3bAppendSection(path, report.String()); err != nil {
		t.Fatalf("append findings section: %v", err)
	}
	t.Logf("appended Track 3b outcome section to %s", path)

	if !anyStructured {
		t.Errorf("no surface produced a structured tool call — coercion did not reach any client response.\n%s",
			strings.Join(summaries, "\n"))
	}
}

func newTrack3bClient() *http.Client {
	return &http.Client{Timeout: 150 * time.Second}
}

// --- per-surface response shapes -------------------------------------------

// track3bAnthropicResp mirrors the Anthropic Messages API response shape
// relevant to tool-use detection. Defined locally (not imported from the
// adapter package) per the harness spec — this test verifies the WIRE shape
// the client actually receives, independent of the adapter's internal types.
type track3bAnthropicResp struct {
	StopReason string `json:"stop_reason"`
	Content    []struct {
		Type  string          `json:"type"`
		Name  string          `json:"name"`
		Input json.RawMessage `json:"input"`
	} `json:"content"`
}

func track3bCheckAnthropic(body string) (bool, string) {
	var r track3bAnthropicResp
	if err := json.Unmarshal([]byte(body), &r); err != nil {
		return false, fmt.Sprintf("decode error: %v", err)
	}
	for _, c := range r.Content {
		if c.Type == "tool_use" && c.Name == "get_weather" {
			if r.StopReason != "tool_use" {
				return false, fmt.Sprintf("tool_use block present but stop_reason=%q (want tool_use), input=%s", r.StopReason, string(c.Input))
			}
			return true, fmt.Sprintf("tool_use name=get_weather input=%s stop_reason=%s", string(c.Input), r.StopReason)
		}
	}
	return false, fmt.Sprintf("no content block with type=tool_use name=get_weather (stop_reason=%q)", r.StopReason)
}

// track3bOpenAIResp mirrors the OpenAI Chat Completions response shape
// relevant to tool-call detection. function.arguments is a JSON-encoded
// STRING per the OpenAI spec.
type track3bOpenAIResp struct {
	Choices []struct {
		FinishReason string `json:"finish_reason"`
		Message      struct {
			ToolCalls []struct {
				Function struct {
					Name      string `json:"name"`
					Arguments string `json:"arguments"`
				} `json:"function"`
			} `json:"tool_calls"`
		} `json:"message"`
	} `json:"choices"`
}

func track3bCheckOpenAI(body string) (bool, string) {
	var r track3bOpenAIResp
	if err := json.Unmarshal([]byte(body), &r); err != nil {
		return false, fmt.Sprintf("decode error: %v", err)
	}
	if len(r.Choices) == 0 {
		return false, "no choices in response"
	}
	ch := r.Choices[0]
	for _, tc := range ch.Message.ToolCalls {
		if tc.Function.Name == "get_weather" {
			if ch.FinishReason != "tool_calls" {
				return false, fmt.Sprintf("tool_calls[0].function.name=get_weather but finish_reason=%q (want tool_calls), arguments=%s",
					ch.FinishReason, tc.Function.Arguments)
			}
			return true, fmt.Sprintf("tool_calls[0].function.name=get_weather arguments=%s finish_reason=%s",
				tc.Function.Arguments, ch.FinishReason)
		}
	}
	return false, fmt.Sprintf("no tool_calls[].function.name=get_weather (finish_reason=%q)", ch.FinishReason)
}

// track3bOllamaResp mirrors the Ollama /api/chat response shape relevant to
// tool-call detection. function.arguments is a JSON OBJECT per the Ollama
// spec (unlike OpenAI's stringified arguments).
type track3bOllamaResp struct {
	Message struct {
		ToolCalls []struct {
			Function struct {
				Name      string          `json:"name"`
				Arguments json.RawMessage `json:"arguments"`
			} `json:"function"`
		} `json:"tool_calls"`
	} `json:"message"`
}

func track3bCheckOllama(body string) (bool, string) {
	var r track3bOllamaResp
	if err := json.Unmarshal([]byte(body), &r); err != nil {
		return false, fmt.Sprintf("decode error: %v", err)
	}
	for _, tc := range r.Message.ToolCalls {
		if tc.Function.Name == "get_weather" {
			var obj map[string]any
			if err := json.Unmarshal(tc.Function.Arguments, &obj); err != nil {
				return false, fmt.Sprintf("tool_calls[0].function.name=get_weather but arguments is not a JSON object: %s (%v)",
					string(tc.Function.Arguments), err)
			}
			return true, fmt.Sprintf("tool_calls[0].function.name=get_weather arguments=%s", string(tc.Function.Arguments))
		}
	}
	return false, "no message.tool_calls[].function.name=get_weather"
}

// --- findings report --------------------------------------------------------

func track3bWriteSection(report *bytes.Buffer, surface, clientResp string, ok bool, detail string) {
	fmt.Fprintf(report, "### %s\n\n", surface)
	fmt.Fprintf(report, "- **Structured tool_call received:** %v\n", ok)
	fmt.Fprintf(report, "- **Detail:** %s\n", detail)
	fmt.Fprintf(report, "\n- Client-visible response (first 400 bytes):\n\n```\n%s\n```\n\n", first(clientResp, 400))
}

// track3bAppendSection appends body under a "Track 3b outcome (live,
// 2026-07-15)" heading to the findings doc at path, mirroring
// track3aAppendSection. Defined as a distinct function (not a redeclaration)
// because track3aAppendSection hardcodes the Track 3a heading text.
func track3bAppendSection(path, body string) error {
	existing, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	var out bytes.Buffer
	out.Write(existing)
	out.WriteString("\n## Track 3b outcome (live, 2026-07-15)\n\n")
	out.WriteString(body)
	return os.WriteFile(path, out.Bytes(), 0o644)
}
