//go:build kirolive

// Track 0 real-kiro capture harness. NOT run in normal CI — build-tag gated.
//
// Prereqs: a gateway running with ACP_CAPTURE=true and real kiro-cli, reachable
// at GW_URL (default http://127.0.0.1:18099). Run:
//
//	KIRO_CMD=kiro-cli ACP_CAPTURE=true HTTP_ADDR=127.0.0.1:18099 \
//	  ENABLED_SURFACES=ollama,anthropic,openai go run ./cmd/otto-gateway &
//	go test -tags kirolive ./tests/ -run TestTrack0Capture -v
//
// It drives one tool round-trip per surface, reads /admin/api/acp-capture,
// classifies kiro's tool-call transport/name-fidelity/JSON-robustness, and
// writes docs/reviews/2026-07-14-track0-toolcall-findings.md.
package tests

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"strings"
	"testing"
	"time"
)

func gwURL() string {
	if v := os.Getenv("GW_URL"); v != "" {
		return v
	}
	return "http://127.0.0.1:18099"
}

type captureFrame struct {
	Seq    uint64 `json:"seq"`
	Method string `json:"method"`
	Params string `json:"params"`
	Bytes  int    `json:"bytes"`
}

type captureResp struct {
	Enabled bool           `json:"enabled"`
	Frames  []captureFrame `json:"frames"`
}

// surfaceProbe is one surface's tool-declaring request.
type surfaceProbe struct {
	name    string
	path    string
	headers map[string]string
	body    string
}

func probes() []surfaceProbe {
	weatherPrompt := "What is the weather in Paris? Use the get_weather tool."
	return []surfaceProbe{
		{
			name: "anthropic", path: "/v1/messages",
			headers: map[string]string{"anthropic-version": "2023-06-01"},
			body: `{"model":"auto","max_tokens":256,"messages":[{"role":"user","content":"` + weatherPrompt + `"}],` +
				`"tools":[{"name":"get_weather","description":"Get weather for a city",` +
				`"input_schema":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}]}`,
		},
		{
			name: "openai", path: "/v1/chat/completions",
			body: `{"model":"auto","messages":[{"role":"user","content":"` + weatherPrompt + `"}],` +
				`"tools":[{"type":"function","function":{"name":"get_weather","description":"Get weather for a city",` +
				`"parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}}]}`,
		},
		{
			name: "ollama", path: "/api/chat",
			body: `{"model":"auto","stream":false,"messages":[{"role":"user","content":"` + weatherPrompt + `"}],` +
				`"tools":[{"type":"function","function":{"name":"get_weather","description":"Get weather for a city",` +
				`"parameters":{"type":"object","properties":{"city":{"type":"string"}},"required":["city"]}}}]}`,
		},
	}
}

func TestTrack0Capture(t *testing.T) {
	client := &http.Client{Timeout: 150 * time.Second}

	// Sanity: capture must be enabled.
	if !fetchCapture(t, client).Enabled {
		t.Fatal("capture is not enabled — start the gateway with ACP_CAPTURE=true")
	}

	var report bytes.Buffer
	fmt.Fprintf(&report, "# Track 0 — kiro tool-call wire findings\n\n**Date:** 2026-07-14\n\n")
	fmt.Fprintf(&report, "Generated by tests/track0_capture_test.go (real kiro). Each surface drove a\n"+
		"`get_weather` tool round-trip; the raw kiro frames captured for that turn are\nclassified below.\n\n")

	for _, p := range probes() {
		before := lastSeq(fetchCapture(t, client))
		resp := drive(t, client, p)
		// Give kiro's trailing frames a moment to land in the ring.
		time.Sleep(1 * time.Second)
		frames := newFramesSince(fetchCapture(t, client), before)

		if len(frames) == 0 {
			t.Errorf("[%s] no frames captured for the round-trip", p.name)
		}
		classifyAndWrite(&report, p.name, resp, frames)
	}

	path := "../docs/reviews/2026-07-14-track0-toolcall-findings.md"
	if err := os.WriteFile(path, report.Bytes(), 0o644); err != nil {
		t.Fatalf("write findings: %v", err)
	}
	t.Logf("wrote findings report to %s", path)
}

func fetchCapture(t *testing.T, c *http.Client) captureResp {
	t.Helper()
	resp, err := c.Get(gwURL() + "/admin/api/acp-capture")
	if err != nil {
		t.Fatalf("GET capture: %v", err)
	}
	defer resp.Body.Close()
	var cr captureResp
	if err := json.NewDecoder(resp.Body).Decode(&cr); err != nil {
		t.Fatalf("decode capture: %v", err)
	}
	return cr
}

func drive(t *testing.T, c *http.Client, p surfaceProbe) string {
	t.Helper()
	req, err := http.NewRequest(http.MethodPost, gwURL()+p.path, strings.NewReader(p.body))
	if err != nil {
		t.Fatalf("[%s] build req: %v", p.name, err)
	}
	req.Header.Set("Content-Type", "application/json")
	for k, v := range p.headers {
		req.Header.Set(k, v)
	}
	resp, err := c.Do(req)
	if err != nil {
		t.Fatalf("[%s] POST %s: %v", p.name, p.path, err)
	}
	defer resp.Body.Close()
	b, _ := io.ReadAll(resp.Body)
	return string(b)
}

func lastSeq(cr captureResp) uint64 {
	var max uint64
	for _, f := range cr.Frames {
		if f.Seq > max {
			max = f.Seq
		}
	}
	return max
}

func newFramesSince(cr captureResp, since uint64) []captureFrame {
	var out []captureFrame
	for _, f := range cr.Frames {
		if f.Seq > since {
			out = append(out, f)
		}
	}
	return out
}

// classifyAndWrite answers the taxonomy for one surface and appends to report.
func classifyAndWrite(report *bytes.Buffer, surface, clientResp string, frames []captureFrame) {
	nativeToolCall := false
	freeTextToolCall := false
	sawDeclaredName := false
	sawKind := false
	var toolMethods []string

	for _, f := range frames {
		lower := strings.ToLower(f.Params)
		if strings.Contains(f.Method, "update") || strings.Contains(f.Method, "notification") {
			if strings.Contains(lower, `"sessionupdate":"tool_call"`) ||
				strings.Contains(lower, `"tool_call_chunk"`) ||
				strings.Contains(lower, `"kind"`) {
				nativeToolCall = true
				toolMethods = append(toolMethods, f.Method)
			}
			if strings.Contains(lower, `{"tool_call"`) || strings.Contains(lower, `\"tool_call\"`) {
				freeTextToolCall = true
			}
		}
		if strings.Contains(f.Params, "get_weather") {
			sawDeclaredName = true
		}
		if strings.Contains(lower, `"kind"`) {
			sawKind = true
		}
	}

	fmt.Fprintf(report, "## %s\n\n", surface)
	fmt.Fprintf(report, "- Frames captured this turn: %d\n", len(frames))
	fmt.Fprintf(report, "- **Transport:** native ACP tool_call=%v, free-text {\"tool_call\":…}=%v\n", nativeToolCall, freeTextToolCall)
	fmt.Fprintf(report, "- **Tool-name fidelity:** declared name (get_weather) seen=%v, kiro `kind` field seen=%v\n", sawDeclaredName, sawKind)
	if len(toolMethods) > 0 {
		fmt.Fprintf(report, "- Tool-bearing notification methods: %s\n", strings.Join(toolMethods, ", "))
	}
	fmt.Fprintf(report, "- Client-visible response (first 400 bytes):\n\n```\n%s\n```\n\n", first(clientResp, 400))
	fmt.Fprintf(report, "<details><summary>raw frames</summary>\n\n```json\n")
	for _, f := range frames {
		fmt.Fprintf(report, "%s %s\n", f.Method, first(f.Params, 600))
	}
	fmt.Fprintf(report, "```\n\n</details>\n\n")
}

func first(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n] + "…"
}
