package openai

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"go.uber.org/goleak"

	"otto-gateway/internal/canonical"
)

// ----------------------------------------------------------------------------
// Golden-fixture infrastructure
//
// Goldens live under internal/adapter/openai/testdata/*.golden and pin
// the byte-exact SSE wire form for OpenAI chat.completion.chunk frames.
// The only non-deterministic component is the 24-hex chatcmpl- message id
// generated by genMessageID(); normalizeChatID substitutes the placeholder
// "chatcmpl-<id>" in both actual and expected before comparing.
//
// Update goldens by re-running the test suite with the GOLDEN_UPDATE=1
// environment variable. The default behavior is read-only — a mismatch
// writes the actual output to a .actual sibling file and fails the test
// with a hint to set GOLDEN_UPDATE=1 after manual inspection.
// ----------------------------------------------------------------------------

// chatIDRegexp captures the genMessageID format "chatcmpl-<24 hex chars>".
// Wider [0-9a-zA-Z]+ instead of {24} tolerates the fallback id
// "chatcmpl-rand_unavailable" which would otherwise miss the substitution.
var chatIDRegexp = regexp.MustCompile(`"id":"chatcmpl-[0-9a-zA-Z_]+"`)

// createdRegexp matches the unix-timestamp "created" field. The value changes
// every second so it must be normalized just like the random id.
var createdRegexp = regexp.MustCompile(`"created":\d+`)

// normalizeChatID replaces the random chatcmpl- id AND the unix-timestamp
// "created" field with stable placeholders so byte-equal comparison stays
// deterministic. Applied to both actual output and golden bytes.
func normalizeChatID(body []byte) []byte {
	out := chatIDRegexp.ReplaceAll(body, []byte(`"id":"chatcmpl-<id>"`))
	out = createdRegexp.ReplaceAll(out, []byte(`"created":0`))
	return out
}

// loadGolden reads the named fixture file from testdata/.
func loadGolden(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("testdata", name)
	b, err := os.ReadFile(path) //nolint:gosec // test fixture path; name is a hardcoded constant from the caller
	if err != nil {
		t.Fatalf("loadGolden %s: %v", name, err)
	}
	return b
}

// compareGolden compares actual bytes against the named golden file
// after chatcmpl-id normalization. On mismatch writes the actual to
// testdata/<name>.actual and fails the test with a hint.
//
// Trailing-newline reconciliation: the repo's pre-commit end-of-file-fixer
// hook collapses trailing blank lines to a single "\n". OpenAI SSE terminates
// with "data: [DONE]\n\n" — so actual wire output ends with TWO newlines
// while the on-disk golden file ends with ONE. We trim trailing newlines from
// BOTH before comparing (mirror anthropic/sse_golden_test.go:79-95).
func compareGolden(t *testing.T, name string, actual []byte) {
	t.Helper()
	norm := bytes.TrimRight(normalizeChatID(actual), "\n")
	want := bytes.TrimRight(loadGolden(t, name), "\n")
	if bytes.Equal(norm, want) {
		return
	}
	actualPath := filepath.Join("testdata", name+".actual")
	if err := os.WriteFile(actualPath, norm, 0o600); err != nil {
		t.Errorf("write %s: %v", actualPath, err)
	}
	t.Fatalf("golden mismatch for %s\n--- want (%s) ---\n%s\n--- got (normalized) ---\n%s\n\n(Actual written to %s. If the diff is intentional, copy actual over the golden file and re-run.)",
		name, name, want, norm, actualPath)
}

// ----------------------------------------------------------------------------
// Fake engine helpers — drive the emitter against a scripted stream
// ----------------------------------------------------------------------------

// fakeStream implements the Stream interface for tests.
type fakeStream struct {
	chunks chan canonical.Chunk
	final  *canonical.FinalResult
	rerr   error
}

func (s *fakeStream) Chunks() <-chan canonical.Chunk {
	return s.chunks
}

func (s *fakeStream) Result() (*canonical.FinalResult, error) {
	return s.final, s.rerr
}

// fakeRunHandle implements the RunHandle interface for tests.
//
// scResp is the synthetic ShortCircuitResponse return value used by Plan 02
// (Phase 08.1 INTEG-01) handler short-circuit tests. Default zero-value nil
// preserves every Plan 01 / pre-08.1 test's behavior: ShortCircuitResponse()
// returns nil → handler falls through to runSSEEmitter as before. Tests that
// need to exercise the streaming short-circuit guard at handlers.go
// (handleChatCompletions ~142-156) set scResp to a non-nil
// *canonical.ChatResponse before calling the handler.
type fakeRunHandle struct {
	stream    *fakeStream
	sessionID string
	scResp    *canonical.ChatResponse
}

func (h *fakeRunHandle) Stream() Stream         { return h.stream }
func (h *fakeRunHandle) SessionID() string      { return h.sessionID }
func (h *fakeRunHandle) StopWatchdog() func() bool { return nil }
func (h *fakeRunHandle) ShortCircuitResponse() *canonical.ChatResponse { return h.scResp }

// nullLogger returns a discard *slog.Logger for tests that don't need log output.
func nullLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, &slog.HandlerOptions{}))
}

// driveGolden runs runSSEEmitter against the supplied chunks + FinalResult
// and returns the response body bytes. Uses model "auto" to match goldens.
// Fixed-size chunks channel + close-after-fill so the emitter sees a clean
// end-of-stream (mirror anthropic/sse_golden_test.go:105-124).
//
// Phase 6: passes an empty canonical.ChatRequest (no tools) so streaming
// coerce is a no-op. Tests that exercise streaming coerce use the
// driveGoldenWithReq variant below to attach tools.
func driveGolden(t *testing.T, chunks []canonical.Chunk, final *canonical.FinalResult) []byte {
	t.Helper()
	return driveGoldenWithReq(t, chunks, final, &canonical.ChatRequest{})
}

// driveGoldenWithReq is the Phase 6 variant of driveGolden that allows
// callers to attach a canonical.ChatRequest with req.Tools populated for
// streaming-coerce tests.
func driveGoldenWithReq(t *testing.T, chunks []canonical.Chunk, final *canonical.FinalResult, req *canonical.ChatRequest) []byte {
	t.Helper()
	ch := make(chan canonical.Chunk, len(chunks)+1) // +1 so close with 0 chunks works
	for _, c := range chunks {
		ch <- c
	}
	close(ch)
	runHandle := &fakeRunHandle{
		stream: &fakeStream{
			chunks: ch,
			final:  final,
		},
		sessionID: "session_golden",
	}
	rec := httptest.NewRecorder()
	if _, err := runSSEEmitter(context.Background(), rec, runHandle, req, "auto", nullLogger()); err != nil {
		t.Fatalf("runSSEEmitter: %v", err)
	}
	return rec.Body.Bytes()
}

// ----------------------------------------------------------------------------
// Golden tests
// ----------------------------------------------------------------------------

// TestSSEGolden pins the full SSE emission sequence for a simple two-chunk
// text-only stream against testdata/sse_text_only.golden:
//   - Frame 1: role delta (delta={"role":"assistant"}, finish_reason=null)
//   - Frame 2: content delta "Hello, "
//   - Frame 3: content delta "world!"
//   - Frame 4: finish_reason frame (delta={}, finish_reason="stop")
//   - Frame 5: data: [DONE]
func TestSSEGolden(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "Hello, "}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "world!"}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGolden(t, chunks, final)
	if os.Getenv("GOLDEN_UPDATE") == "1" {
		norm := bytes.TrimRight(normalizeChatID(body), "\n")
		if err := os.WriteFile(filepath.Join("testdata", "sse_text_only.golden"), norm, 0o600); err != nil {
			t.Fatalf("update golden: %v", err)
		}
		t.Log("golden updated: testdata/sse_text_only.golden")
		return
	}
	compareGolden(t, "sse_text_only.golden", body)
}

// ----------------------------------------------------------------------------
// Phase 6 streaming-coerce + kiro-native-text-delta + iteration-3 fixtures
//
// These five tests lock the Phase 6 wire-shape contract for the OpenAI SSE
// emitter:
//   - TestSSE_Golden_StreamingCoerce_BareJSON — buffered JSON text →
//     multi-frame delta.tool_calls + finish_reason:"tool_calls" (REVIEW HIGH #1)
//   - TestSSE_Golden_KiroNative_TextDelta — kiro-native ChunkKindToolCall
//     renders as text-delta "[tool: <name>]\n" narration; NO delta.tool_calls
//     anywhere; terminal finish_reason is NOT "tool_calls" (REVIEW HIGH #2)
//   - TestSSE_Golden_ToolCallFirst_RoleEmitOnce — role frame fires exactly
//     once even when tool_call is the first chunk (REVIEW LOW #8)
//   - TestStream_NativeToolCall_ThenJSONText_NoCoerce — kiro-native then JSON
//     text: sawKiroNativeToolCall blocks coerce; buffered text flushed as
//     plain text-deltas; finish_reason:"stop" (iteration-3 HIGH #2 fix)
//   - TestStream_NativeToolCall_Only_NoCoerce — kiro-native only: narration
//     emitted, no text to flush, finish_reason:"stop" (iteration-3 HIGH #2 fix)
//
// Assertions are inline byte-level substring checks rather than full golden
// files — the wire-shape canaries (delta.tool_calls absent for kiro-native,
// JSON-string arguments shape for coerce-synthesized) are easier to express
// and read as substring checks than as fragile byte-exact goldens.
// ----------------------------------------------------------------------------

// makeReqWithTools builds a *canonical.ChatRequest with a single
// get_weather tool (the canonical Phase 6 test fixture).
func makeReqWithTools() *canonical.ChatRequest {
	return &canonical.ChatRequest{
		Tools: []canonical.ToolSpec{
			{
				Name:        "get_weather",
				Description: "Get the weather for a location",
				Parameters: map[string]any{
					"type": "object",
					"properties": map[string]any{
						"location": map[string]any{"type": "string"},
					},
					"required": []any{"location"},
				},
			},
		},
	}
}

// TestSSE_Golden_StreamingCoerce_BareJSON locks REVIEW HIGH #1: when the
// stream emits text fragments that accumulate into bare JSON matching a
// declared tool's properties, the emitter buffers the text deltas, calls
// engine.CoerceToolCall at stream end, and emits the multi-frame
// delta.tool_calls + finish_reason:"tool_calls" SSE shape INSTEAD of the
// buffered text frames. No coerced text should leak.
func TestSSE_Golden_StreamingCoerce_BareJSON(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "{"}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: `"location":`}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: `"NYC"`}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "}"}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGoldenWithReq(t, chunks, final, makeReqWithTools())
	out := string(body)

	// Role frame must appear exactly once.
	if got := bytes.Count(body, []byte(`"role":"assistant"`)); got != 1 {
		t.Errorf("role frame count: got %d, want 1; body=%q", got, out)
	}

	// Multi-frame delta.tool_calls (frame B id+name, frame C arguments) MUST appear.
	if !strings.Contains(out, `"tool_calls"`) {
		t.Errorf("expected delta.tool_calls frames in output; body=%q", out)
	}
	if !strings.Contains(out, `"name":"get_weather"`) {
		t.Errorf("expected get_weather tool name in output; body=%q", out)
	}
	// JSON-STRING arguments (escape-quoted location value).
	if !strings.Contains(out, `"arguments":"{\"location\":\"NYC\"}"`) {
		// Or the alternative key-ordering — both are acceptable since
		// json.Marshal of map[string]any has no order guarantee.
		if !strings.Contains(out, `"arguments":"{\"location\":\"NYC\"}"`) {
			t.Errorf("expected JSON-string arguments shape; body=%q", out)
		}
	}

	// Terminal finish_reason MUST be "tool_calls".
	if !strings.Contains(out, `"finish_reason":"tool_calls"`) {
		t.Errorf("expected terminal finish_reason:tool_calls; body=%q", out)
	}

	// Buffered text fragments must NOT leak — none of the raw JSON
	// fragments should appear as a plain text-delta frame.
	// We check for delta.content carrying any of the buffered fragments.
	for _, frag := range []string{`"delta":{"content":"{"}`, `"delta":{"content":"\"location\":"}`, `"delta":{"content":"\"NYC\""}`, `"delta":{"content":"}"}`} {
		if strings.Contains(out, frag) {
			t.Errorf("buffered text fragment must NOT leak on coerce hit; found %q in body=%q", frag, out)
		}
	}

	// data: [DONE] terminator.
	if !strings.Contains(out, "data: [DONE]") {
		t.Errorf("expected data: [DONE] terminator; body=%q", out)
	}
}

// TestSSE_Golden_KiroNative_TextDelta locks REVIEW HIGH #2: kiro-native
// ChunkKindToolCall renders as a text-delta narration line ("[tool: <name>]\n")
// — NOT a native delta.tool_calls frame. The output must contain NO
// delta.tool_calls frames and the terminal finish_reason must NOT be
// "tool_calls" (coerce did not fire).
func TestSSE_Golden_KiroNative_TextDelta(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "I'll check. "}},
		{Kind: canonical.ChunkKindToolCall, ToolCall: &canonical.ToolCallChunk{
			ID:   "tc_1",
			Name: "get_weather",
			Args: map[string]any{"location": "NYC"},
		}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: " Done."}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGoldenWithReq(t, chunks, final, makeReqWithTools())
	out := string(body)

	// Role frame exactly once.
	if got := bytes.Count(body, []byte(`"role":"assistant"`)); got != 1 {
		t.Errorf("role frame count: got %d, want 1; body=%q", got, out)
	}

	// All three text-delta fragments appear.
	if !strings.Contains(out, `"delta":{"content":"I'll check. "}`) {
		t.Errorf("expected 'I'll check. ' text delta; body=%q", out)
	}
	if !strings.Contains(out, `"delta":{"content":"[tool: get_weather]\n"}`) {
		t.Errorf("expected [tool: get_weather] text delta; body=%q", out)
	}
	if !strings.Contains(out, `"delta":{"content":" Done."}`) {
		t.Errorf("expected ' Done.' text delta; body=%q", out)
	}

	// NO native delta.tool_calls anywhere.
	if strings.Contains(out, `"tool_calls"`) {
		t.Errorf("kiro-native path must NOT emit delta.tool_calls; body=%q", out)
	}

	// Terminal finish_reason is NOT "tool_calls".
	if strings.Contains(out, `"finish_reason":"tool_calls"`) {
		t.Errorf("kiro-native-only path must NOT have finish_reason:tool_calls; body=%q", out)
	}
	if !strings.Contains(out, `"finish_reason":"stop"`) {
		t.Errorf("expected terminal finish_reason:stop; body=%q", out)
	}

	// data: [DONE] terminator.
	if !strings.Contains(out, "data: [DONE]") {
		t.Errorf("expected data: [DONE] terminator; body=%q", out)
	}
}

// TestSSE_Golden_ToolCallFirst_RoleEmitOnce locks REVIEW LOW #8: when a
// tool_call chunk is the FIRST chunk in the stream (no preceding text),
// the role frame is still emitted exactly once before the tool_call
// text-delta frame.
func TestSSE_Golden_ToolCallFirst_RoleEmitOnce(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindToolCall, ToolCall: &canonical.ToolCallChunk{
			ID:   "tc_1",
			Name: "get_weather",
			Args: map[string]any{"location": "NYC"},
		}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGoldenWithReq(t, chunks, final, makeReqWithTools())
	out := string(body)

	// Role frame appears exactly once.
	if got := bytes.Count(body, []byte(`"role":"assistant"`)); got != 1 {
		t.Errorf("role frame count: got %d, want exactly 1; body=%q", got, out)
	}

	// Narration text-delta appears.
	if !strings.Contains(out, `"delta":{"content":"[tool: get_weather]\n"}`) {
		t.Errorf("expected [tool: get_weather] narration; body=%q", out)
	}

	// No native delta.tool_calls.
	if strings.Contains(out, `"tool_calls"`) {
		t.Errorf("tool_call-first must NOT emit delta.tool_calls; body=%q", out)
	}

	// data: [DONE] terminator.
	if !strings.Contains(out, "data: [DONE]") {
		t.Errorf("expected data: [DONE] terminator; body=%q", out)
	}
}

// TestStream_NativeToolCall_ThenJSONText_NoCoerce locks the iteration-3
// HIGH #2 fix: if a kiro-native ChunkKindToolCall fires during the stream,
// sawKiroNativeToolCall is set true. Any subsequent JSON-shaped text gets
// buffered, but at stream end the buffered text is FLUSHED as plain
// text-delta frames (NOT coerced into a tool_call). The terminal
// finish_reason is "stop", NOT "tool_calls".
func TestStream_NativeToolCall_ThenJSONText_NoCoerce(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindToolCall, ToolCall: &canonical.ToolCallChunk{
			ID:   "tc_1",
			Name: "get_weather",
			Args: map[string]any{"location": "NYC"},
		}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "{"}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: `"location":`}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: `"Tokyo"`}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "}"}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGoldenWithReq(t, chunks, final, makeReqWithTools())
	out := string(body)

	// Narration line for kiro-native.
	if !strings.Contains(out, `"delta":{"content":"[tool: get_weather]\n"}`) {
		t.Errorf("expected [tool: get_weather] narration; body=%q", out)
	}

	// Buffered text MUST be released as plain text-delta frames.
	for _, frag := range []string{`"delta":{"content":"{"}`, `"delta":{"content":"\"location\":"}`, `"delta":{"content":"\"Tokyo\""}`, `"delta":{"content":"}"}`} {
		if !strings.Contains(out, frag) {
			t.Errorf("expected buffered fragment to be released; missing %q in body=%q", frag, out)
		}
	}

	// NO native delta.tool_calls.
	if strings.Contains(out, `"tool_calls"`) {
		t.Errorf("sawKiroNativeToolCall=true must skip coerce; no delta.tool_calls allowed; body=%q", out)
	}

	// finish_reason is "stop", NOT "tool_calls".
	if strings.Contains(out, `"finish_reason":"tool_calls"`) {
		t.Errorf("must NOT emit finish_reason:tool_calls; body=%q", out)
	}
	if !strings.Contains(out, `"finish_reason":"stop"`) {
		t.Errorf("expected terminal finish_reason:stop; body=%q", out)
	}

	// data: [DONE] terminator.
	if !strings.Contains(out, "data: [DONE]") {
		t.Errorf("expected data: [DONE] terminator; body=%q", out)
	}
}

// TestStream_NativeToolCall_Only_NoCoerce locks iteration-3 HIGH #2 fix
// for the kiro-native-only scenario (no surrounding text). The narration
// fires, sawKiroNativeToolCall=true, no buffered text, terminal
// finish_reason is "stop".
func TestStream_NativeToolCall_Only_NoCoerce(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindToolCall, ToolCall: &canonical.ToolCallChunk{
			ID:   "tc_1",
			Name: "get_weather",
			Args: map[string]any{"location": "NYC"},
		}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGoldenWithReq(t, chunks, final, makeReqWithTools())
	out := string(body)

	// Role + narration.
	if got := bytes.Count(body, []byte(`"role":"assistant"`)); got != 1 {
		t.Errorf("role frame count: got %d, want 1; body=%q", got, out)
	}
	if !strings.Contains(out, `"delta":{"content":"[tool: get_weather]\n"}`) {
		t.Errorf("expected [tool: get_weather] narration; body=%q", out)
	}

	// NO native delta.tool_calls.
	if strings.Contains(out, `"tool_calls"`) {
		t.Errorf("kiro-native-only must NOT emit delta.tool_calls; body=%q", out)
	}

	// finish_reason is "stop", NOT "tool_calls".
	if strings.Contains(out, `"finish_reason":"tool_calls"`) {
		t.Errorf("must NOT emit finish_reason:tool_calls; body=%q", out)
	}
	if !strings.Contains(out, `"finish_reason":"stop"`) {
		t.Errorf("expected terminal finish_reason:stop; body=%q", out)
	}

	// data: [DONE] terminator.
	if !strings.Contains(out, "data: [DONE]") {
		t.Errorf("expected data: [DONE] terminator; body=%q", out)
	}
}

// TestStream_ProseThenJSON_NoCoerce_NoLeak (WR-01 regression): when a
// non-JSON-shaped text chunk has already flushed as a plain text-delta
// frame, a subsequent JSON-shaped chunk MUST NOT retroactively engage
// the streaming-coerce buffer. The output must NOT carry delta.tool_calls
// or finish_reason:"tool_calls" — coerce did not (and cannot safely)
// fire once prose has reached the wire.
//
// This locks the Pitfall 3 "entire text" invariant in the SSE streaming
// path: a split stream (prose first, JSON second) is not a valid coerce
// candidate.
func TestStream_ProseThenJSON_NoCoerce_NoLeak(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "Here's the answer: "}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: `{"location":"NYC"}`}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGoldenWithReq(t, chunks, final, makeReqWithTools())
	out := string(body)

	// Prose preamble must reach the wire as a plain text-delta frame.
	if !strings.Contains(out, `"delta":{"content":"Here's the answer: "}`) {
		t.Errorf("WR-01: prose preamble must flush as text-delta; body=%q", out)
	}
	// The JSON fragment must ALSO reach the wire as a plain text-delta
	// (released, NOT silently swallowed by the buffer).
	if !strings.Contains(out, `"delta":{"content":"{\"location\":\"NYC\"}"}`) {
		t.Errorf("WR-01: JSON fragment must flush as text-delta; body=%q", out)
	}
	// Coerce MUST NOT fire — no delta.tool_calls anywhere.
	if strings.Contains(out, `"tool_calls"`) {
		t.Errorf("WR-01: prose-then-JSON must not fire streaming coerce; body=%q", out)
	}
	// finish_reason is "stop", NOT "tool_calls".
	if strings.Contains(out, `"finish_reason":"tool_calls"`) {
		t.Errorf("WR-01: must NOT emit finish_reason:tool_calls on prose-then-JSON; body=%q", out)
	}
	if !strings.Contains(out, `"finish_reason":"stop"`) {
		t.Errorf("WR-01: expected terminal finish_reason:stop; body=%q", out)
	}
}

// TestNormalizeChatID verifies the regex+substitute path rewrites a
// realistic genMessageID output correctly.
func TestNormalizeChatID(t *testing.T) {
	defer goleak.VerifyNone(t)
	raw := []byte(`{"id":"chatcmpl-abcdef0123456789abcdef01"}`)
	want := []byte(`{"id":"chatcmpl-<id>"}`)
	got := normalizeChatID(raw)
	if !bytes.Equal(got, want) {
		t.Errorf("normalize: got %q, want %q", got, want)
	}
	// Idempotent on pre-normalized payload.
	already := []byte(`{"id":"chatcmpl-<id>"}`)
	if !bytes.Equal(normalizeChatID(already), already) {
		t.Error("normalize must be idempotent on pre-normalized payload")
	}
}
