package openai

import (
	"bytes"
	"context"
	"io"
	"log/slog"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"testing"

	"go.uber.org/goleak"

	"otto-gateway/internal/canonical"
)

// ----------------------------------------------------------------------------
// Golden-fixture infrastructure
//
// Goldens live under internal/adapter/openai/testdata/*.golden and pin
// the byte-exact SSE wire form for OpenAI chat.completion.chunk frames.
// The only non-deterministic component is the 24-hex chatcmpl- message id
// generated by genMessageID(); normalizeChatID substitutes the placeholder
// "chatcmpl-<id>" in both actual and expected before comparing.
//
// Update goldens by re-running the test suite with the GOLDEN_UPDATE=1
// environment variable. The default behavior is read-only — a mismatch
// writes the actual output to a .actual sibling file and fails the test
// with a hint to set GOLDEN_UPDATE=1 after manual inspection.
// ----------------------------------------------------------------------------

// chatIDRegexp captures the genMessageID format "chatcmpl-<24 hex chars>".
// Wider [0-9a-zA-Z]+ instead of {24} tolerates the fallback id
// "chatcmpl-rand_unavailable" which would otherwise miss the substitution.
var chatIDRegexp = regexp.MustCompile(`"id":"chatcmpl-[0-9a-zA-Z_]+"`)

// createdRegexp matches the unix-timestamp "created" field. The value changes
// every second so it must be normalized just like the random id.
var createdRegexp = regexp.MustCompile(`"created":\d+`)

// normalizeChatID replaces the random chatcmpl- id AND the unix-timestamp
// "created" field with stable placeholders so byte-equal comparison stays
// deterministic. Applied to both actual output and golden bytes.
func normalizeChatID(body []byte) []byte {
	out := chatIDRegexp.ReplaceAll(body, []byte(`"id":"chatcmpl-<id>"`))
	out = createdRegexp.ReplaceAll(out, []byte(`"created":0`))
	return out
}

// loadGolden reads the named fixture file from testdata/.
func loadGolden(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("testdata", name)
	b, err := os.ReadFile(path) //nolint:gosec // test fixture path; name is a hardcoded constant from the caller
	if err != nil {
		t.Fatalf("loadGolden %s: %v", name, err)
	}
	return b
}

// compareGolden compares actual bytes against the named golden file
// after chatcmpl-id normalization. On mismatch writes the actual to
// testdata/<name>.actual and fails the test with a hint.
//
// Trailing-newline reconciliation: the repo's pre-commit end-of-file-fixer
// hook collapses trailing blank lines to a single "\n". OpenAI SSE terminates
// with "data: [DONE]\n\n" — so actual wire output ends with TWO newlines
// while the on-disk golden file ends with ONE. We trim trailing newlines from
// BOTH before comparing (mirror anthropic/sse_golden_test.go:79-95).
func compareGolden(t *testing.T, name string, actual []byte) {
	t.Helper()
	norm := bytes.TrimRight(normalizeChatID(actual), "\n")
	want := bytes.TrimRight(loadGolden(t, name), "\n")
	if bytes.Equal(norm, want) {
		return
	}
	actualPath := filepath.Join("testdata", name+".actual")
	if err := os.WriteFile(actualPath, norm, 0o600); err != nil {
		t.Errorf("write %s: %v", actualPath, err)
	}
	t.Fatalf("golden mismatch for %s\n--- want (%s) ---\n%s\n--- got (normalized) ---\n%s\n\n(Actual written to %s. If the diff is intentional, copy actual over the golden file and re-run.)",
		name, name, want, norm, actualPath)
}

// ----------------------------------------------------------------------------
// Fake engine helpers — drive the emitter against a scripted stream
// ----------------------------------------------------------------------------

// fakeStream implements the Stream interface for tests.
type fakeStream struct {
	chunks chan canonical.Chunk
	final  *canonical.FinalResult
	rerr   error
}

func (s *fakeStream) Chunks() <-chan canonical.Chunk {
	return s.chunks
}

func (s *fakeStream) Result() (*canonical.FinalResult, error) {
	return s.final, s.rerr
}

// fakeRunHandle implements the RunHandle interface for tests.
type fakeRunHandle struct {
	stream    *fakeStream
	sessionID string
}

func (h *fakeRunHandle) Stream() Stream         { return h.stream }
func (h *fakeRunHandle) SessionID() string      { return h.sessionID }
func (h *fakeRunHandle) StopWatchdog() func() bool { return nil }

// nullLogger returns a discard *slog.Logger for tests that don't need log output.
func nullLogger() *slog.Logger {
	return slog.New(slog.NewTextHandler(io.Discard, &slog.HandlerOptions{}))
}

// driveGolden runs runSSEEmitter against the supplied chunks + FinalResult
// and returns the response body bytes. Uses model "auto" to match goldens.
// Fixed-size chunks channel + close-after-fill so the emitter sees a clean
// end-of-stream (mirror anthropic/sse_golden_test.go:105-124).
func driveGolden(t *testing.T, chunks []canonical.Chunk, final *canonical.FinalResult) []byte {
	t.Helper()
	ch := make(chan canonical.Chunk, len(chunks)+1) // +1 so close with 0 chunks works
	for _, c := range chunks {
		ch <- c
	}
	close(ch)
	runHandle := &fakeRunHandle{
		stream: &fakeStream{
			chunks: ch,
			final:  final,
		},
		sessionID: "session_golden",
	}
	rec := httptest.NewRecorder()
	if err := runSSEEmitter(context.Background(), rec, runHandle, "auto", nullLogger()); err != nil {
		t.Fatalf("runSSEEmitter: %v", err)
	}
	return rec.Body.Bytes()
}

// ----------------------------------------------------------------------------
// Golden tests
// ----------------------------------------------------------------------------

// TestSSEGolden pins the full SSE emission sequence for a simple two-chunk
// text-only stream against testdata/sse_text_only.golden:
//   - Frame 1: role delta (delta={"role":"assistant"}, finish_reason=null)
//   - Frame 2: content delta "Hello, "
//   - Frame 3: content delta "world!"
//   - Frame 4: finish_reason frame (delta={}, finish_reason="stop")
//   - Frame 5: data: [DONE]
func TestSSEGolden(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "Hello, "}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "world!"}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGolden(t, chunks, final)
	if os.Getenv("GOLDEN_UPDATE") == "1" {
		norm := bytes.TrimRight(normalizeChatID(body), "\n")
		if err := os.WriteFile(filepath.Join("testdata", "sse_text_only.golden"), norm, 0o600); err != nil {
			t.Fatalf("update golden: %v", err)
		}
		t.Log("golden updated: testdata/sse_text_only.golden")
		return
	}
	compareGolden(t, "sse_text_only.golden", body)
}

// TestNormalizeChatID verifies the regex+substitute path rewrites a
// realistic genMessageID output correctly.
func TestNormalizeChatID(t *testing.T) {
	defer goleak.VerifyNone(t)
	raw := []byte(`{"id":"chatcmpl-abcdef0123456789abcdef01"}`)
	want := []byte(`{"id":"chatcmpl-<id>"}`)
	got := normalizeChatID(raw)
	if !bytes.Equal(got, want) {
		t.Errorf("normalize: got %q, want %q", got, want)
	}
	// Idempotent on pre-normalized payload.
	already := []byte(`{"id":"chatcmpl-<id>"}`)
	if !bytes.Equal(normalizeChatID(already), already) {
		t.Error("normalize must be idempotent on pre-normalized payload")
	}
}
