package anthropic

import (
	"bytes"
	"context"
	"net/http/httptest"
	"os"
	"path/filepath"
	"regexp"
	"strings"
	"testing"

	"go.uber.org/goleak"

	"otto-gateway/internal/canonical"
)

// ----------------------------------------------------------------------------
// Golden-fixture infrastructure
//
// Goldens live under internal/adapter/anthropic/testdata/*.golden and pin
// the byte-exact SSE wire form. The only non-deterministic component is the
// 24-hex random message id generated by genMessageID(); normalizeMessageID
// substitutes the placeholder "msg_01<id>" in both actual and expected
// before comparing.
//
// Update goldens by re-running the test suite with the GOLDEN_UPDATE=1
// environment variable. The default behavior is read-only — a mismatch
// writes the actual output to a .actual sibling file and fails the test
// with a hint to set GOLDEN_UPDATE=1 after manual inspection.
// ----------------------------------------------------------------------------

// messageIDRegexp captures the genMessageID format `msg_01<24 hex chars>`.
// Wider [0-9a-f]+ instead of {24} tolerates the fallback id
// `msg_01_rand_unavailable` which would otherwise miss the substitution
// (though that path is only reached on a crypto/rand failure).
var messageIDRegexp = regexp.MustCompile(`"id":"msg_01[0-9a-fA-F_]+"`)

// normalizeMessageID replaces the random message id substring with a
// stable placeholder so byte-equal comparison stays deterministic.
// Applied to both actual output and golden bytes (the golden file ships
// the placeholder; normalizing actual is the load-bearing step).
func normalizeMessageID(body []byte) []byte {
	return messageIDRegexp.ReplaceAll(body, []byte(`"id":"msg_01<id>"`))
}

// loadGolden reads the named fixture file from testdata/.
//
// G304 is intentionally silenced here: `name` is a hardcoded
// test-file string from the caller (sse_text_only.golden etc.),
// never user input. The .golden files are checked into the repo
// under internal/adapter/anthropic/testdata/ — there is no
// tainted-input path here.
func loadGolden(t *testing.T, name string) []byte {
	t.Helper()
	path := filepath.Join("testdata", name)
	b, err := os.ReadFile(path) //nolint:gosec // test fixture path; name is a constant string from the caller
	if err != nil {
		t.Fatalf("loadGolden %s: %v", name, err)
	}
	return b
}

// compareGolden compares actual bytes against the named golden file
// after message-id normalization. On mismatch writes the actual to
// testdata/<name>.actual and fails the test with a diff-friendly
// hint.
//
// Trailing-newline reconciliation: the repo's pre-commit
// end-of-file-fixer hook collapses any trailing run of blank lines
// down to a single terminating "\n". Anthropic's SSE wire format
// terminates EVERY frame (including the final message_stop) with
// "\n\n" — so the canonical wire output ends with TWO newlines while
// the on-disk golden file ends with ONE. We reconcile by trimming
// trailing newlines from BOTH actual and want before comparing —
// the byte-equality of the meaningful prefix is what matters; the
// final newline run is an artifact of the test-fixture-on-disk vs.
// wire-on-the-network representation.
func compareGolden(t *testing.T, name string, actual []byte) {
	t.Helper()
	norm := bytes.TrimRight(normalizeMessageID(actual), "\n")
	want := bytes.TrimRight(loadGolden(t, name), "\n")
	if bytes.Equal(norm, want) {
		return
	}
	// Write the actual (post-normalization, post-trim) output to a
	// .actual sibling for the developer to inspect alongside the
	// expected.
	actualPath := filepath.Join("testdata", name+".actual")
	if err := os.WriteFile(actualPath, norm, 0o600); err != nil {
		t.Errorf("write %s: %v", actualPath, err)
	}
	t.Fatalf("golden mismatch for %s\n--- want (%s) ---\n%s\n--- got (normalized) ---\n%s\n\n(Actual written to %s. If the diff is intentional, copy actual over the golden file and re-run.)",
		name, name, want, norm, actualPath)
}

// ----------------------------------------------------------------------------
// Helper — drive the real runSSEEmitter against a scripted stream
// ----------------------------------------------------------------------------

// driveGolden runs runSSEEmitter against the supplied chunks +
// FinalResult and returns the response body bytes. Uses model "auto"
// to match the goldens. Fixed-size chunks channel + close-after-fill
// so runSSEEmitterLoop sees a clean end-of-stream.
func driveGolden(t *testing.T, chunks []canonical.Chunk, final *canonical.FinalResult) []byte {
	t.Helper()
	ch := make(chan canonical.Chunk, len(chunks))
	for _, c := range chunks {
		ch <- c
	}
	close(ch)
	runHandle := &fakeRunHandle{
		stream: &fakeStream{
			chunks: ch,
			final:  final,
		},
		sessionID: "session_golden",
	}
	rec := httptest.NewRecorder()
	if _, err := runSSEEmitter(context.Background(), rec, runHandle, nil, "auto", 0, nullLogger()); err != nil {
		t.Fatalf("runSSEEmitter: %v", err)
	}
	return rec.Body.Bytes()
}

// ----------------------------------------------------------------------------
// Golden tests
// ----------------------------------------------------------------------------

// TestSSESequenceGolden_TextOnly pins the full SSE event sequence for
// a simple text-only stream against testdata/sse_text_only.golden.
func TestSSESequenceGolden_TextOnly(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "Hello, "}},
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "world!"}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGolden(t, chunks, final)
	compareGolden(t, "sse_text_only.golden", body)
}

// TestSSESequenceGolden_TextThenThinking pins the SSE event sequence
// for a text→thinking kind transition. Verifies block 0 (text) opens,
// fills, closes; block 1 (thinking) opens, fills, closes; then
// message_delta + message_stop. Golden lives at
// testdata/sse_text_then_thinking.golden.
func TestSSESequenceGolden_TextThenThinking(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "hi"}},
		{Kind: canonical.ChunkKindThought, Thought: &canonical.ThoughtChunk{Content: "reasoning"}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGolden(t, chunks, final)
	compareGolden(t, "sse_text_then_thinking.golden", body)
}

// TestSSESequenceGolden_MessageStartFrame pins just the leading
// message_start frame (with empty content / null stop_reason / zero
// usage) against testdata/sse_message_start.golden. Acts as a unit
// pin for the message_start payload shape so failures in the full
// sequence goldens can be localized to either message_start drift OR
// content-block drift.
func TestSSESequenceGolden_MessageStartFrame(t *testing.T) {
	defer goleak.VerifyNone(t)
	// Empty chunk stream → only message_start, message_delta, message_stop
	// are emitted. The golden contains ONLY the message_start frame,
	// so we slice the body after the first \n\n separator.
	body := driveGolden(t, nil, &canonical.FinalResult{StopReason: canonical.StopEndTurn})
	// Find the end of the first SSE frame (`\n\n`).
	sep := []byte("\n\n")
	idx := bytes.Index(body, sep)
	if idx < 0 {
		t.Fatalf("no frame separator in body; body=%q", body)
	}
	firstFrame := body[:idx+len(sep)]
	compareGolden(t, "sse_message_start.golden", firstFrame)
}

// TestSSE_Golden_ToolUse pins the byte-level Anthropic SSE sequence
// for kiro-native tool_call chunks per Phase 6 Plan 04 D-07. Drives a
// fake stream `[text-chunk("I'll check weather. "), tool_call-chunk(
// id=toolu_01, name=get_weather, args={location:"NYC"})]` and asserts:
//   - content_block_start for the tool_use block with `"input":{}`
//     LITERAL on the wire (CR-01 pointer-to-empty-map; Pitfall 1
//     guards against `"input":null`).
//   - content_block_delta with input_json_delta carrying the full
//     args JSON in partial_json.
//   - content_block_stop, then message_delta with stop_reason set to
//     `"tool_use"` (NOT `"end_turn"` — the toolUseEmitted finalizer
//     override per Task 2 behavior).
//   - Block-index sequence 0,0,0,0,1,1,1 (Pitfall 7 — exactly one
//     bump on the text->tool_use kind transition).
func TestSSE_Golden_ToolUse(t *testing.T) {
	defer goleak.VerifyNone(t)
	chunks := []canonical.Chunk{
		{Kind: canonical.ChunkKindText, Text: &canonical.TextChunk{Content: "I'll check weather. "}},
		{Kind: canonical.ChunkKindToolCall, ToolCall: &canonical.ToolCallChunk{
			ID:   "toolu_01",
			Name: "get_weather",
			Args: map[string]any{"location": "NYC"},
		}},
	}
	final := &canonical.FinalResult{StopReason: canonical.StopEndTurn}
	body := driveGolden(t, chunks, final)

	// Byte-level CR-01 assertions: must carry `"input":{}` literal AND
	// must NOT carry `"input":null` anywhere.
	if !bytes.Contains(body, []byte(`"input":{}`)) {
		t.Errorf("wire missing required `\"input\":{}` literal for tool_use content_block_start (CR-01 pointer-to-empty-map); body:\n%s", body)
	}
	if bytes.Contains(body, []byte(`"input":null`)) {
		t.Errorf("wire carries forbidden `\"input\":null` (Pitfall 1 — Anthropic SDK rejects null input); body:\n%s", body)
	}

	// stop_reason override (Task 2 toolUseEmitted finalizer): the
	// streaming finalizer MUST emit `"stop_reason":"tool_use"` even
	// when the engine's FinalResult.StopReason is StopEndTurn — the
	// presence of a tool_use block overrides the mapping.
	if !bytes.Contains(body, []byte(`"stop_reason":"tool_use"`)) {
		t.Errorf("wire missing required `\"stop_reason\":\"tool_use\"` on message_delta (finalizer override); body:\n%s", body)
	}
	if bytes.Contains(body, []byte(`"stop_reason":"end_turn"`)) {
		t.Errorf("wire carries forbidden `\"stop_reason\":\"end_turn\"` on message_delta — tool_use override missing; body:\n%s", body)
	}

	// Event sequence: message_start, content_block_start(text),
	// content_block_delta(text), content_block_stop, content_block_start(tool_use),
	// content_block_delta(input_json_delta), content_block_stop, message_delta, message_stop.
	events := sseEventLines(string(body))
	want := []string{
		"message_start",
		"content_block_start",
		"content_block_delta",
		"content_block_stop",
		"content_block_start",
		"content_block_delta",
		"content_block_stop",
		"message_delta",
		"message_stop",
	}
	if !equalSlice(events, want) {
		t.Errorf("event sequence: got %v, want %v", events, want)
	}

	// input_json_delta is the discriminator on the tool_use delta.
	if !bytes.Contains(body, []byte(`"input_json_delta"`)) {
		t.Errorf("wire missing input_json_delta discriminator on tool_use content_block_delta; body:\n%s", body)
	}
	// The args JSON should be present in partial_json. encoding/json
	// produces deterministic key order for map[string]any (sorted), so
	// {"location":"NYC"} renders as `{\"location\":\"NYC\"}` inside
	// partial_json (which itself is a JSON string).
	if !bytes.Contains(body, []byte(`"partial_json":"{\"location\":\"NYC\"}"`)) {
		t.Errorf("wire missing expected partial_json carrying tool args; body:\n%s", body)
	}

	// Block-index discipline (Pitfall 7): exactly one bump on the
	// text -> tool_use kind transition. Scan data lines for the
	// `"index":N` field on each frame and assert the sequence is
	// 0,0,0,1,1,1 (content_block_start, content_block_delta,
	// content_block_stop for block 0; then content_block_start,
	// content_block_delta, content_block_stop for block 1; the
	// message_start / message_delta / message_stop frames have no
	// index field).
	idxRe := regexp.MustCompile(`"index":(\d+)`)
	matches := idxRe.FindAllSubmatch(body, -1)
	gotIdx := make([]string, 0, len(matches))
	for _, m := range matches {
		gotIdx = append(gotIdx, string(m[1]))
	}
	wantIdx := []string{"0", "0", "0", "1", "1", "1"}
	if !equalSlice(gotIdx, wantIdx) {
		t.Errorf("block-index sequence: got %v, want %v (Pitfall 7: exactly one bump per kind transition)", gotIdx, wantIdx)
	}
}

// TestNormalizeMessageID_RegressionPin verifies the regex+substitute
// path actually rewrites a realistic genMessageID output. Defensive
// pin so the goldens don't quietly regress if genMessageID changes
// shape (e.g., to 32 hex chars).
func TestNormalizeMessageID_RegressionPin(t *testing.T) {
	defer goleak.VerifyNone(t)
	raw := []byte(`{"id":"msg_01abcdef0123456789abcdef01","other":"keep"}`)
	want := []byte(`{"id":"msg_01<id>","other":"keep"}`)
	got := normalizeMessageID(raw)
	if !bytes.Equal(got, want) {
		t.Errorf("normalize: got %q, want %q", got, want)
	}
	// Sanity: an already-normalized payload is idempotent.
	already := []byte(`{"id":"msg_01<id>","other":"keep"}`)
	if !bytes.Equal(normalizeMessageID(already), already) {
		t.Error("normalize must be idempotent on pre-normalized payload")
	}
	// Sanity: genMessageID's actual output normalizes correctly.
	actualID := genMessageID()
	if !strings.HasPrefix(actualID, "msg_01") {
		t.Fatalf("genMessageID prefix: got %q, want msg_01...", actualID)
	}
	withReal := []byte(`{"id":"` + actualID + `"}`)
	wantReal := []byte(`{"id":"msg_01<id>"}`)
	if !bytes.Equal(normalizeMessageID(withReal), wantReal) {
		t.Errorf("normalize real id: got %q, want %q", normalizeMessageID(withReal), wantReal)
	}
}
